"use client"
import React, { useState } from "react";
import { HoverBorderGradient } from "./ui/hover-border-gradient";
import { SparklesText } from "./magicui/sparkles-text";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Sparkles, ChevronLeft, ChevronRight } from "lucide-react";

const showcaseItems = [
  {
    id: "1",
    type: "image",
    src: "/images/showcase-1.jpg",
    alt: "AI-generated fantasy landscape",
    title: "Fantasy Landscape",
    description: "A vibrant, AI-crafted world with lush forests and glowing skies, created from a simple text prompt."
  },
  {
    id: "2",
    type: "video",
    src: "/videos/showcase-2.mp4",
    alt: "AI-generated promotional video",
    title: "Promotional Video",
    description: "A dynamic 30-second ad clip generated from text, perfect for social media marketing."
  },
  {
    id: "3",
    type: "image",
    src: "/images/showcase-3.jpg",
    alt: "AI-generated portrait",
    title: "Futuristic Portrait",
    description: "A stunning, high-resolution portrait of a cyberpunk character, brought to life by Pictora AI."
  },
  {
    id: "4",
    type: "image",
    src: "/images/showcase-4.jpg",
    alt: "AI-generated abstract art",
    title: "Abstract Art",
    description: "Unique abstract artwork generated from a creative prompt, ideal for prints or digital displays."
  },
  {
    id: "5",
    type: "video",
    src: "/videos/showcase-5.mp4",
    alt: "AI-generated animation",
    title: "Short Animation",
    description: "A captivating animated sequence created effortlessly with Pictora AI’s video tools."
  }
];

export function Showcase() {
  const [currentIndex, setCurrentIndex] = useState(0);

  const nextSlide = () => {
    setCurrentIndex((prev) => (prev + 1) % showcaseItems.length);
  };

  const prevSlide = () => {
    setCurrentIndex((prev) => (prev - 1 + showcaseItems.length) % showcaseItems.length);
  };

  return (
    <div className="mt-32 px-4 md:px-6 lg:px-8 relative">
      <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-primary/5" />

      {/* Header */}
      <div className="relative z-10 space-y-4 text-center py-8">
        <div className="flex items-center justify-center">
          <HoverBorderGradient
            containerClassName="rounded-full"
            as="button"
            className="flex items-center space-x-2"
            aria-label="Explore Showcase"
          >
            <Sparkles className="h-4 w-4" />
            <span className="font-semibold">Showcase</span>
          </HoverBorderGradient>
        </div>
        <div className="flex items-center justify-center">
          <SparklesText>See What You Can Create</SparklesText>
        </div>
        <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
          Explore stunning examples of images and videos generated by Pictora AI. Turn your ideas into reality!
        </p>
      </div>

      {/* Desktop Grid */}
      <div className="relative z-10 hidden md:grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-7xl mx-auto">
        {showcaseItems.map((item) => (
          <Card
            key={item.id}
            className="group relative overflow-hidden border-2 hover:border-primary/20 transition-all duration-300 hover:shadow-lg hover:shadow-primary/5 bg-gradient-to-br from-background to-muted/20"
          >
            <CardHeader className="p-0">
              {item.type === "image" ? (
                <img
                  src={item.src}
                  alt={item.alt}
                  className="w-full h-48 object-cover rounded-t-lg"
                />
              ) : (
                <video
                  src={item.src}
                  muted
                  loop
                  autoPlay
                  className="w-full h-48 object-cover rounded-t-lg"
                />
              )}
            </CardHeader>
            <CardContent className="pt-4">
              <CardTitle className="text-lg group-hover:text-primary transition-colors">
                {item.title}
              </CardTitle>
              <CardDescription className="text-sm leading-relaxed mt-2">
                {item.description}
              </CardDescription>
            </CardContent>
            <div className="absolute inset-0 bg-gradient-to-r from-primary/5 via-transparent to-primary/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none" />
          </Card>
        ))}
      </div>

      {/* Mobile Carousel */}
      <div className="relative z-10 md:hidden max-w-md mx-auto">
        <div className="relative overflow-hidden">
          <Card
            className="group relative border-2 hover:border-primary/20 transition-all duration-300 bg-gradient-to-br from-background to-muted/20"
          >
            <CardHeader className="p-0">
              {showcaseItems[currentIndex].type === "image" ? (
                <img
                  src={showcaseItems[currentIndex].src}
                  alt={showcaseItems[currentIndex].alt}
                  className="w-full h-64 object-cover rounded-t-lg"
                />
              ) : (
                <video
                  src={showcaseItems[currentIndex].src}
                  muted
                  loop
                  autoPlay
                  className="w-full h-64 object-cover rounded-t-lg"
                />
              )}
            </CardHeader>
            <CardContent className="pt-4">
              <CardTitle className="text-lg group-hover:text-primary transition-colors">
                {showcaseItems[currentIndex].title}
              </CardTitle>
              <CardDescription className="text-sm leading-relaxed mt-2">
                {showcaseItems[currentIndex].description}
              </CardDescription>
            </CardContent>
            <div className="absolute inset-0 bg-gradient-to-r from-primary/5 via-transparent to-primary/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none" />
          </Card>
          <button
            onClick={prevSlide}
            aria-label="Previous slide"
            className="absolute left-2 top-1/2 transform -translate-y-1/2 bg-gray-800/50 hover:bg-gray-800/70 text-white p-2 rounded-full"
          >
            <ChevronLeft className="h-5 w-5" />
          </button>
          <button
            onClick={nextSlide}
            aria-label="Next slide"
            className="absolute right-2 top-1/2 transform -translate-y-1/2 bg-gray-800/50 hover:bg-gray-800/70 text-white p-2 rounded-full"
          >
            <ChevronRight className="h-5 w-5" />
          </button>
        </div>
        <div className="flex justify-center mt-4 space-x-2">
          {showcaseItems.map((_, index) => (
            <button
              key={index}
              onClick={() => setCurrentIndex(index)}
              className={`h-2 w-2 rounded-full ${index === currentIndex ? 'bg-primary' : 'bg-gray-300'}`}
              aria-label={`Go to slide ${index + 1}`}
            />
          ))}
        </div>
      </div>

      {/* Call to Action */}
      <div className="relative z-10 mt-16 text-center">
        <Button
          className="bg-primary hover:bg-primary/90"
          onClick={() => window.location.href = '/signup'}
        >
          Start Creating Your Own
        </Button>
        <p className="text-muted-foreground mt-4 text-sm">
          Join creators worldwide and bring your visions to life with Pictora AI.
        </p>
      </div>
    </div>
  );
}